version: '3'

services:
  md-homepage:
    build: .
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=munich-developer.de
      - LETSENCRYPT_HOST=munich-developer.de
      - LETSENCRYPT_EMAIL=johannes.hinkov@gmail.com
    networks:
      - auto-proxy

networks:
  auto-proxy:
    external: true